name: Package
on:
  workflow_call:
    inputs:
      version:
        description: SourceGit package version
        required: true
        type: string
jobs:
  windows:
    name: Package Windows
    runs-on: windows-2022
    strategy:
      matrix:
        runtime: [win-x64]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
      - name: Download build
        uses: actions/download-artifact@v8
        with:
          name: sourcegit.${{ matrix.runtime }}
          path: build/SourceGit
      - name: Package
        shell: pwsh
        env:
          VERSION: ${{ inputs.version }}
          RUNTIME: ${{ matrix.runtime }}
        run: ./build/scripts/package.win.ps1
      - name: Upload package artifact
        uses: actions/upload-artifact@v7
        with:
          name: package.${{ matrix.runtime }}
          path: build/sourcegit_*.zip
      - name: Delete temp artifacts
        uses: geekyeggo/delete-artifact@v6
        with:
          name: sourcegit.${{ matrix.runtime }}
